#!/usr/bin/with-contenv bash

VOLUME=${VOLUME:-"volume"}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=`id -u abc`
GROUP=`id -g abc`

if [ `stat -c %u /volume` != "${OWNER}" ]; then
    chown ${OWNER} /volume
fi
if [ `stat -c %g /volume` != "${GROUP}" ]; then
    chgrp ${GROUP} /volume
fi

[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
pid file = /var/run/rsyncd.pid
log file = /dev/stdout
[${VOLUME}]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = /volume
    comment = ${VOLUME}
EOF

